# Generated by Django 5.1.2 on 2024-11-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrenchNews',
            fields=[
                ('central_id', models.IntegerField(primary_key='True', serialize=False)),
                ('media_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
